'use client';

import ReportChart from '@/components/admin/reports/ReportChart';
import { formatReportDate, formatReportMetric } from '@/lib/reportFormat';
import { cn } from '@/lib/cn';

function PreviewTable({ table }) {
  if (!table?.columns?.length) return null;
  const rows = (table.rows || []).slice(0, 15);
  return (
    <div className="overflow-x-auto rounded-md border border-neutral-200">
      <table className="w-full text-left text-[12px]">
        <thead>
          <tr className="border-b border-neutral-200 bg-neutral-50">
            {table.columns.map((col) => (
              <th
                key={col.id}
                className={cn(
                  'px-3 py-2 font-semibold text-neutral-700',
                  col.align === 'right' && 'text-right',
                )}
              >
                {col.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => (
            <tr key={ri} className="border-b border-neutral-100 last:border-0">
              {table.columns.map((col) => (
                <td
                  key={col.id}
                  className={cn(
                    'px-3 py-2 text-neutral-600',
                    col.align === 'right' && 'text-right tabular-nums',
                  )}
                >
                  {row[col.key] ?? '—'}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      {(table.rows || []).length > 15 ? (
        <p className="px-3 py-2 text-[11px] text-neutral-500 italic">
          Showing 15 of {table.rows.length} rows. Excel export includes full data.
        </p>
      ) : null}
    </div>
  );
}

export default function ReportPreviewPanel({ data, loading, error }) {
  if (loading) {
    return (
      <div className="w-full rounded-xl border border-neutral-800 bg-neutral-900/30 p-8 min-h-[420px] flex items-center justify-center">
        <p className="text-sm text-neutral-500">Building preview…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="w-full rounded-xl border border-red-900/50 bg-neutral-900/30 p-8 min-h-[420px] flex items-center justify-center">
        <p className="text-sm text-red-400">{error}</p>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="w-full rounded-xl border border-neutral-800 bg-neutral-900/30 p-8 min-h-[420px] flex items-center justify-center">
        <p className="text-sm text-neutral-500">Select options to preview the report.</p>
      </div>
    );
  }

  return (
    <div className="w-full">
      <div className="rounded-xl border border-neutral-800 bg-neutral-900/30 p-4 md:p-6">
        <div className="mx-auto max-w-[900px] rounded-lg bg-white text-neutral-900 shadow-2xl shadow-black/30">
        <div className="border-b border-neutral-200 px-6 py-5">
          <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-neutral-500">
            {data.brand || 'Novel Centre'}
          </p>
          <h2 className="mt-1 font-headline-xl text-[22px] font-semibold text-neutral-900">{data.title}</h2>
          <div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 text-[12px]">
            <div>
              <span className="text-neutral-500">Period</span>
              <p className="font-medium text-neutral-800">{data.period?.label}</p>
            </div>
            <div>
              <span className="text-neutral-500">Generated</span>
              <p className="font-medium text-neutral-800">{formatReportDate(data.generatedAt)}</p>
            </div>
            <div className="col-span-2">
              <span className="text-neutral-500">Generated By</span>
              <p className="font-medium text-neutral-800">{data.generatedBy}</p>
            </div>
          </div>
        </div>

        <div className="px-6 py-5 space-y-6">
          <section>
            <h3 className="text-[13px] font-semibold uppercase tracking-wider text-neutral-700 mb-3">
              Executive Summary
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {(data.executiveSummary || []).map((m) => (
                <div
                  key={m.label}
                  className="rounded-md border border-neutral-200 bg-neutral-50 px-3 py-3"
                >
                  <p className="text-[10px] uppercase tracking-wide text-neutral-500">{m.label}</p>
                  <p className="mt-1 text-lg font-semibold tabular-nums text-neutral-900">
                    {formatReportMetric(m)}
                  </p>
                </div>
              ))}
            </div>
          </section>

          {(data.sections || []).map((sec) => (
            <section key={sec.id} className="space-y-3">
              <h3 className="text-[13px] font-semibold text-neutral-800 border-b border-neutral-100 pb-2">
                {sec.title}
              </h3>
              {sec.chart ? <ReportChart chart={sec.chart} /> : null}
              {sec.note ? <p className="text-[11px] italic text-neutral-500">{sec.note}</p> : null}
              {sec.table ? <PreviewTable table={sec.table} /> : null}
            </section>
          ))}

          {!data.sections?.length ? (
            <p className="text-sm text-neutral-500">
              No chart sections selected. Choose sections above or export for full spreadsheet data.
            </p>
          ) : null}
        </div>

        <div className="border-t border-neutral-200 px-6 py-3 flex justify-between text-[10px] text-neutral-500">
          <span>Generated by Novel Centre Admin · Confidential</span>
          <span>Live preview</span>
        </div>
        </div>
      </div>
    </div>
  );
}
