'use strict';

const ExcelJS = require('exceljs');

function dateOnly(d) {
  const x = new Date(d);
  if (Number.isNaN(x.getTime())) return null;
  return x.toISOString().slice(0, 10);
}

function rangeClause(column, from, to, params) {
  params.push(from, to);
  return `${column} >= ? AND ${column} < DATE_ADD(?, INTERVAL 1 DAY)`;
}

function inr(n) {
  const v = Number(n) || 0;
  return v;
}

function pct(part, whole) {
  const w = Number(whole) || 0;
  if (!w) return 0;
  return Number(((Number(part) || 0) / w).toFixed(4));
}

function monthKey(d) {
  const x = new Date(d);
  return `${x.getUTCFullYear()}-${String(x.getUTCMonth() + 1).padStart(2, '0')}`;
}

async function newWorkbook() {
  return new ExcelJS.Workbook();
}

function styleHeader(row) {
  row.font = { bold: true };
  row.commit?.();
}

function addSheet(wb, name) {
  const ws = wb.addWorksheet(name.slice(0, 31));
  return ws;
}

function writeKvSheet(ws, title, pairs) {
  ws.addRow([title]);
  ws.addRow([]);
  ws.addRow(['Field', 'Value']);
  styleHeader(ws.getRow(3));
  for (const [k, v] of pairs) ws.addRow([k, v]);
}

function writeTable(ws, headers, rows) {
  ws.addRow(headers);
  styleHeader(ws.getRow(1));
  for (const r of rows) ws.addRow(r);
  ws.columns.forEach((col) => {
    let max = 10;
    col.eachCell({ includeEmpty: true }, (cell) => {
      const len = String(cell.value ?? '').length;
      if (len > max) max = Math.min(len, 40);
    });
    col.width = max + 2;
  });
}

async function toBuffer(wb) {
  return Buffer.from(await wb.xlsx.writeBuffer());
}

function metaPairs({ reportName, from, to, generatedBy, extra = [] }) {
  return [
    ['Report Name', reportName],
    ['Period From', from],
    ['Period To', to],
    ['Generated At', new Date().toISOString()],
    ['Generated By', generatedBy || 'Admin'],
    ['Currency', 'INR'],
    ...extra,
  ];
}

module.exports = {
  dateOnly,
  rangeClause,
  inr,
  pct,
  monthKey,
  newWorkbook,
  addSheet,
  writeKvSheet,
  writeTable,
  toBuffer,
  metaPairs,
  styleHeader,
};
