'use strict';

const path = require('path');
const fs = require('fs');
const PDFDocument = require('pdfkit');
const { preview, formatMetricValue } = require('./preview');
const { formatGeneratedDate } = require('./format');

// margin:0 so absolute footer drawing never auto-paginates
const MARGIN = 48;
const CONTENT_BOTTOM = 780;
const MAX_TABLE_ROWS = 12;
const MAX_SECTIONS = 4;

const FONT_DIR = path.join(__dirname, '../../../assets/fonts');
const FONT_REGULAR = path.join(FONT_DIR, 'NotoSans-Regular.ttf');
const FONT_BOLD = path.join(FONT_DIR, 'NotoSans-Bold.ttf');

function textAt(doc, str, x, y, opts = {}) {
  const { width, align } = opts;
  doc.text(String(str ?? ''), x, y, {
    lineBreak: false,
    ...(width != null ? { width, align: align || 'left' } : {}),
  });
}

function collectBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function ensureSpace(doc, y, need) {
  if (y + need > CONTENT_BOTTOM) {
    doc.addPage();
    return MARGIN + 10;
  }
  return y;
}

function setupFonts(doc) {
  if (!fs.existsSync(FONT_REGULAR) || !fs.existsSync(FONT_BOLD)) {
    const err = new Error('Report fonts missing (NotoSans). Run deploy with server/assets/fonts.');
    err.status = 500;
    throw err;
  }
  doc.registerFont('ReportSans', FONT_REGULAR);
  doc.registerFont('ReportSans-Bold', FONT_BOLD);
  return { regular: 'ReportSans', bold: 'ReportSans-Bold' };
}

function drawHeader(doc, data, fonts) {
  const pageW = doc.page.width;
  const t = textAt;

  doc.font(fonts.bold).fontSize(10).fillColor('#888888');
  t(doc, data.brand || 'Novel Centre', MARGIN, MARGIN);

  doc.font(fonts.bold).fontSize(20).fillColor('#111111');
  t(doc, data.title, MARGIN, MARGIN + 16);

  const metaY = MARGIN + 48;
  doc.font(fonts.regular).fontSize(10).fillColor('#444444');
  t(doc, 'Period:', MARGIN, metaY);
  doc.font(fonts.bold);
  t(doc, data.period?.label || '', MARGIN + 52, metaY);

  doc.font(fonts.regular);
  t(doc, 'Generated:', MARGIN, metaY + 16);
  doc.font(fonts.bold);
  t(doc, formatGeneratedDate(new Date(data.generatedAt)), MARGIN + 68, metaY + 16);

  doc.font(fonts.regular);
  t(doc, 'Generated By:', MARGIN + 260, metaY + 16);
  doc.font(fonts.bold);
  t(doc, data.generatedBy || 'Admin', MARGIN + 340, metaY + 16, {
    width: pageW - MARGIN - 340,
  });

  doc.moveTo(MARGIN, metaY + 40)
    .lineTo(pageW - MARGIN, metaY + 40)
    .strokeColor('#dddddd')
    .stroke();
  return metaY + 54;
}

function drawExecutiveSummary(doc, y, summary, fonts) {
  y = ensureSpace(doc, y, 120);
  doc.font(fonts.bold).fontSize(12).fillColor('#111111');
  textAt(doc, 'Executive Summary', MARGIN, y);
  y += 22;

  const cols = Math.min(Math.max(summary.length, 1), 4);
  const colW = (doc.page.width - MARGIN * 2) / cols;
  summary.forEach((m, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = MARGIN + col * colW;
    const cardY = y + row * 52;
    doc.roundedRect(x, cardY, colW - 8, 44, 4).fillAndStroke('#f7f7f7', '#e8e8e8');
    doc.font(fonts.regular).fontSize(8).fillColor('#666666');
    textAt(doc, m.label, x + 10, cardY + 8, { width: colW - 20 });
    doc.font(fonts.bold).fontSize(12).fillColor('#111111');
    textAt(doc, formatMetricValue(m), x + 10, cardY + 22, { width: colW - 20 });
  });

  const rows = Math.ceil(summary.length / cols);
  return y + rows * 52 + 12;
}

function drawBarChart(doc, x, y, w, h, items, { labelKey, valueKey }, fonts) {
  if (!items?.length) return y + h;
  const max = Math.max(...items.map((d) => Number(d[valueKey]) || 0), 1);
  const slot = w / items.length;
  const barW = Math.min(slot * 0.65, 36);
  items.slice(0, 8).forEach((d, i) => {
    const val = Number(d[valueKey]) || 0;
    const barH = Math.max(2, (val / max) * (h - 24));
    const bx = x + i * slot + (slot - barW) / 2;
    doc.rect(bx, y + h - barH - 18, barW, barH).fill('#1a1a1a');
    const label = String(d[labelKey] || '').slice(0, 14);
    doc.font(fonts.regular).fontSize(7).fillColor('#666666');
    textAt(doc, label, bx - 6, y + h - 14, { width: barW + 12, align: 'center' });
  });
  return y + h + 6;
}

function drawLineChart(doc, x, y, w, h, items, { valueKey }) {
  if (!items?.length) return y + h;
  const slice = items.slice(-10);
  const max = Math.max(...slice.map((d) => Number(d[valueKey]) || 0), 1);
  const step = slice.length > 1 ? w / (slice.length - 1) : w;
  doc.strokeColor('#1a1a1a').lineWidth(1.5);
  slice.forEach((d, i) => {
    const val = Number(d[valueKey]) || 0;
    const px = x + i * step;
    const py = y + h - 18 - (val / max) * (h - 28);
    if (i === 0) doc.moveTo(px, py);
    else doc.lineTo(px, py);
  });
  doc.stroke();
  return y + h + 6;
}

function drawTable(doc, y, table, fonts, maxRows = MAX_TABLE_ROWS) {
  if (!table?.columns?.length) return y;
  const rows = (table.rows || []).slice(0, maxRows);
  const tableW = doc.page.width - MARGIN * 2;
  const colW = tableW / table.columns.length;

  y = ensureSpace(doc, y, 28 + rows.length * 16);
  table.columns.forEach((col, i) => {
    const x = MARGIN + i * colW;
    doc.font(fonts.bold).fontSize(8).fillColor('#333333');
    textAt(doc, col.label, x + 4, y, {
      width: colW - 8,
      align: col.align === 'right' ? 'right' : 'left',
    });
  });
  y += 14;
  doc.moveTo(MARGIN, y).lineTo(doc.page.width - MARGIN, y).strokeColor('#cccccc').stroke();
  y += 6;

  rows.forEach((row) => {
    y = ensureSpace(doc, y, 16);
    table.columns.forEach((col, i) => {
      const x = MARGIN + i * colW;
      doc.font(fonts.regular).fontSize(8).fillColor('#444444');
      textAt(doc, row[col.key] ?? '', x + 4, y, {
        width: colW - 8,
        align: col.align === 'right' ? 'right' : 'left',
      });
    });
    y += 14;
  });

  if ((table.rows || []).length > maxRows) {
    doc.font(fonts.regular).fontSize(7).fillColor('#888888');
    textAt(
      doc,
      `Showing ${maxRows} of ${table.rows.length} rows. Export Excel for full data.`,
      MARGIN,
      y + 4,
    );
    y += 16;
  }
  return y + 8;
}

function drawSection(doc, y, sec, fonts) {
  y = ensureSpace(doc, y, 80);
  doc.font(fonts.bold).fontSize(11).fillColor('#111111');
  textAt(doc, sec.title, MARGIN, y);
  y += 18;

  if (sec.chart?.items?.length) {
    const chartH = 90;
    y = ensureSpace(doc, y, chartH + 10);
    if (sec.chart.type === 'line') {
      y = drawLineChart(doc, MARGIN, y, doc.page.width - MARGIN * 2, chartH, sec.chart.items, sec.chart);
    } else {
      y = drawBarChart(
        doc,
        MARGIN,
        y,
        doc.page.width - MARGIN * 2,
        chartH,
        sec.chart.items,
        sec.chart,
        fonts,
      );
    }
    y += 6;
  }

  if (sec.note) {
    doc.font(fonts.regular).fontSize(8).fillColor('#666666');
    textAt(doc, sec.note, MARGIN, y, { width: doc.page.width - MARGIN * 2 });
    y += 14;
  }

  if (sec.table) y = drawTable(doc, y, sec.table, fonts);
  return y + 10;
}

function addFooters(doc, fonts) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    const pageNum = i - range.start + 1;
    const footerY = doc.page.height - 32;
    const pageW = doc.page.width - MARGIN * 2;
    doc.font(fonts.regular).fontSize(8).fillColor('#888888');
    textAt(doc, 'Generated by Novel Centre Admin', MARGIN, footerY);
    textAt(doc, 'Confidential', MARGIN, footerY + 10);
    textAt(doc, `Page ${pageNum} of ${range.count}`, MARGIN, footerY, {
      width: pageW,
      align: 'right',
    });
  }
}

async function generatePdf(type, opts) {
  const data = await preview(type, opts);
  const doc = new PDFDocument({
    size: 'A4',
    margin: 0,
    bufferPages: true,
    autoFirstPage: true,
  });

  const fonts = setupFonts(doc);

  let y = drawHeader(doc, data, fonts);
  y = drawExecutiveSummary(doc, y, data.executiveSummary || [], fonts);

  const sections = (data.sections || []).slice(0, MAX_SECTIONS);
  for (const sec of sections) {
    y = drawSection(doc, y, sec, fonts);
  }

  if (!sections.length) {
    doc.font(fonts.regular).fontSize(10).fillColor('#666666');
    textAt(doc, 'No chart sections selected. Executive summary only.', MARGIN, y);
  }

  addFooters(doc, fonts);

  const buffer = await collectBuffer(doc);
  return {
    buffer,
    filename: `${type}-report_${data.period.from}_to_${data.period.to}.pdf`,
    contentType: 'application/pdf',
  };
}

module.exports = { generatePdf };
