'use strict';

function fieldId(label) {
  return label
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()))
    .join('');
}

function fields(labels) {
  return labels.map((label) => ({ id: fieldId(label), label }));
}

function tab(id, label, fieldLabels, opts = {}) {
  return {
    id,
    label,
    kind: opts.kind || 'table',
    fields: fields(fieldLabels),
  };
}

const META_FIELDS = [
  'Report Name', 'Period From', 'Period To', 'Generated At', 'Generated By', 'Currency',
];

const REPORT_SCHEMAS = [
  {
    id: 'wallet-coin',
    title: 'Wallet & Coin Report',
    description: 'Coin ledger, wallet balances, sources, and outstanding liability.',
    tabs: [
      tab('summary', 'Summary', ['Metric', 'Value']),
      tab('coin-ledger', 'Coin Ledger', [
        'Ledger ID', 'Date', 'User ID', 'Username', 'Wallet ID', 'Transaction Type', 'Coin Source',
        'Coins In', 'Coins Out', 'Balance After', 'Related Transaction ID', 'Related Novel', 'Related Chapter', 'Remarks',
      ]),
      tab('wallet-balances', 'Wallet Balances', [
        'Wallet ID', 'User ID', 'Username', 'Purchased Coins', 'Bonus Coins', 'Promotional Coins',
        'Total Balance', 'Last Activity', 'Wallet Status',
      ]),
      tab('coin-sources-usage', 'Coin Sources & Usage', ['Source', 'Coins', '%']),
      tab('liability-summary', 'Liability Summary', ['Category', 'Coins']),
      tab('report-information', 'Report Information', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'transaction',
    title: 'Transaction Report',
    description: 'Payment orders, refunds, payouts, and gateway summary.',
    tabs: [
      tab('summary', 'Summary', ['Metric', 'Value', 'Type', 'Count', 'Amount']),
      tab('transactions', 'Transactions', [
        'Transaction ID', 'Date', 'Time', 'Order ID', 'User ID', 'Username', 'Email', 'Transaction Type',
        'Payment Method', 'Gateway', 'Amount', 'Currency', 'Coins Added', 'Bonus Coins', 'Discount',
        'Coupon Code', 'Tax', 'Gateway Fee', 'Net Amount', 'Status', 'Country', 'Platform', 'Device',
        'Created By', 'Remarks',
      ]),
      tab('refunds', 'Refunds', [
        'Refund ID', 'Original Transaction ID', 'Refund Date', 'User ID', 'Username',
        'Original Amount', 'Refund Amount', 'Currency', 'Refund Reason', 'Refund Status',
        'Approved By', 'Gateway Reference', 'Notes',
      ]),
      tab('payouts', 'Payouts', [
        'Payout ID', 'Authour ID', 'Author Name', 'Period', 'Chapters Sold', 'Coins Earned',
        'Gross Amount', 'Tax Deduction', 'Platform Commission', 'Net Payable', 'Payment Method',
        'Payment Status', 'Payment Date', 'Reference Number', 'Notes',
      ]),
      tab('payment-gateway-summary', 'Payment Gateway Summary', [
        'Gateway', 'Transactions', 'Success', 'Failed', 'Amount', 'Gateway Fee',
      ]),
      tab('metadata', 'Metadata', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'sales',
    title: 'Sales Report',
    description: 'Sales ledger, monetization performance, and customer insights.',
    tabs: [
      tab('summary', 'Summary', ['Metric', 'Value']),
      tab('sales-ledger', 'Sales Ledger', [
        'Sale ID', 'Order ID', 'Transaction ID', 'Date', 'User ID', 'Username', 'Product Category',
        'Product Name', 'Quantity', 'Unit Price', 'Discount', 'Tax', 'Final Amount', 'Currency',
        'Payment Method', 'Platform', 'Status',
      ]),
      tab('monetization-performance', 'Monetization Performance', [
        'Product', 'Units Sold', 'Revenue', 'Avg Selling Price',
      ]),
      tab('customer-insights', 'Customer Insights', ['Metric', 'Value']),
      tab('report-information', 'Report Information', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'revenue',
    title: 'Revenue Report',
    description: 'Daily revenue, sources, payment methods, and top products.',
    tabs: [
      tab('summary', 'Summary', ['Metric', 'Value']),
      tab('daily-revenue', 'Daily Revenue', [
        'Date', 'Orders', 'Gross Revenue', 'Refunds', 'Net Revenue', 'Avg Order Value',
      ]),
      tab('revenue-sources', 'Revenue Sources', ['Source', 'Orders', 'Revenue', '%']),
      tab('payment-methods', 'Payment Methods', ['Payment Method', 'Orders', 'Revenue', 'Percentage']),
      tab('top-selling-products', 'Top Selling Products', [
        'Product', 'Category', 'Quantity Sold', 'Revenue',
      ]),
    ],
  },
  {
    id: 'tax',
    title: 'Tax Report',
    description: 'GST tax lines by transaction, jurisdiction, and product.',
    tabs: [
      tab('tax-transactions', 'Tax Transactions', [
        'Tax Record ID', 'Transaction ID', 'Invoice No.', 'Order ID', 'Transaction Date', 'User ID', 'Username',
        'Country', 'State/Province', 'Currency', 'Exchange Rate', 'Product Type', 'Product Name', 'Quantity',
        'Subtotal (Before Tax)', 'Tax Type', 'Tax Rate (%)', 'Tax Amount', 'Total Paid', 'Payment Gateway',
        'Payment Method', 'Payment Status', 'Filing Status', 'Filing Period', 'Created By', 'Remarks',
      ]),
      tab('tax-summary', 'Tax Summary', ['Metric', 'Example', 'Month', 'Sales', 'Tax', 'Total']),
      tab('tax-by-jurisdiction', 'Tax by Jurisdiction', [
        'Country', 'State', 'Currency', 'Sales', 'Tax', 'Transactions',
      ]),
      tab('product-tax-summary', 'Product Tax Summary', [
        'Product Type', 'Product Name', 'Sales', 'Tax', 'Transactions',
      ]),
      tab('metadata', 'Metadata', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'promotion-coupon',
    title: 'Promotion & Coupon Report',
    description: 'Coupon redemptions and campaign performance.',
    tabs: [
      tab('promotion-transactions', 'Promotion Transactions', [
        'Promotion Record ID', 'Transaction ID', 'Invoice No.', 'Order ID', 'Transaction Date', 'User ID', 'Username',
        'Promotion Type', 'Promotion Name', 'Coupon Code', 'Product Type', 'Product Name', 'Original Price',
        'Discount Type', 'Discount Value', 'Discount Amount', 'Final Price', 'Tax Amount', 'Total Paid', 'Currency',
        'Payment Gateway', 'Payment Status', 'Campaign ID', 'Notes',
      ]),
      tab('promotion-summary', 'Promotion Summary', [
        'KPI', 'Example', 'Month', 'Orders', 'Discount', 'Revenue',
      ]),
      tab('coupon-performance', 'Coupon Performance', [
        'Coupon Code', 'Coupon Name', 'Discount Type', 'Discount Value', 'Usage Count', 'Unique Users',
        'Revenue Generated', 'Discount Given', 'Avg Discount', 'Start Date', 'End Date', 'Status',
      ]),
      tab('campaign-performance', 'Campaign Performance', [
        'Campaign ID', 'Campaign Name', 'Campaign Type', 'Start Date', 'End Date', 'Orders',
        'Revenue Before Discount', 'Discount Given', 'Revenue After Discount', 'Avg Order Value',
        'Conversion Rate', 'Status',
      ]),
      tab('metadata', 'Metadata', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'reconciliation',
    title: 'Reconciliation Report',
    description: 'Gateway settlement matching and exceptions.',
    tabs: [
      tab('reconciliation-records', 'Reconciliation Records', [
        'Reconciliation ID', 'Transaction ID', 'Order ID', 'Invoice No.', 'Transaction Date', 'Settlement Date',
        'User ID', 'Username', 'Payment Gateway', 'Gateway Transaction ID', 'Gateway Settlement ID', 'Currency',
        'Gross Amount', 'Gateway Fee', 'Tax on Gateway Fee', 'Net Settlement', 'Expected Settlement',
        'Settlement Difference', 'Reconciliation Status', 'Settlement Status', 'Reconciled By', 'Reconciled On', 'Notes',
      ]),
      tab('reconciliation-summary', 'Reconciliation Summary', [
        'KPI', 'Example', 'Month', 'Gross', 'Net', 'Fees', 'Pending',
      ]),
      tab('gateway-settlement-summary', 'Gateway Settlement Summary', [
        'Gateway', 'Transactions', 'Gross Amount', 'Gateway Fees', 'Net Settlement',
        'Pending Settlements', 'Failed Settlements', 'Average Fee', 'Reconciliation Rate',
      ]),
      tab('exceptions-mismatches', 'Exceptions & Mismatches', [
        'Transaction ID', 'Gateway', 'Issue Type', 'Expected Amount', 'Actual Amount', 'Difference',
        'Status', 'Assigned To', 'Resolution Date', 'Resolution Notes',
      ]),
      tab('metadata', 'Metadata', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'author-payout',
    title: 'Author Payout Report',
    description: 'Author payouts, royalty breakdown, and contract payments.',
    tabs: [
      tab('summary', 'Summary', ['Metric', 'Value', 'Status', 'Count', 'Amount']),
      tab('payout-ledger', 'Payout Ledger', [
        'Payout ID', 'Author ID', 'Pen Name', 'Agreement Type', 'Payout Type', 'Payment Period',
        'Gross Amount', 'Deductions', 'Net Amount', 'Currency', 'Status', 'Payment Method',
        'Bank Reference', 'Created Date', 'Paid Date', 'Approved By', 'Notes',
      ]),
      tab('royalty-breakdown', 'Royalty Breakdown', [
        'Royalty ID', 'Author', 'Novel', 'Reporting Period', 'Gross Novel Revenue', 'Platform Deductions',
        'Net Revenue', 'Royalty %', 'Royalty Amount', 'Settlement Status', 'Available Date', 'Paid Date',
      ]),
      tab('contract-payments', 'Contract Payments', [
        'Contract Payment ID', 'Author', 'Agreement Type', 'Novel', 'Payment Basis', 'Units', 'Rate',
        'Gross Amount', 'Status', 'Payment Date', 'Bank Reference', 'Notes',
      ]),
      tab('report-information', 'Report Information', META_FIELDS, { kind: 'kv' }),
    ],
  },
  {
    id: 'financial-audit',
    title: 'Financial Audit Report',
    description: 'Admin financial actions and high-risk activity.',
    tabs: [
      tab('financial-audit-log', 'Financial Audit Log', [
        'Audit ID', 'Date & Time', 'User Type', 'User ID', 'Username', 'Action Category', 'Action', 'Module',
        'Record ID', 'Previous Value', 'New Value', 'Difference', 'Reason', 'IP Address', 'Device', 'Session ID',
        'Status', 'Approval Required', 'Approved By', 'Approval Date', 'Notes',
      ]),
      tab('audit-summary', 'Audit Summary', [
        'KPI', 'Example', 'Month', 'Actions', 'Manual', 'Automatic', 'High Risk',
      ]),
      tab('admin-activity-summary', 'Admin Activity Summary', [
        'Admin ID', 'Username', 'Total Actions', 'Payments Modified', 'Payouts Approved',
        'Wallet Adjustments', 'Coupon Changes', 'Subscription Changes', 'High-Risk Actions', 'Last Activity',
      ]),
      tab('high-risk-activities', 'High-Risk Activities', [
        'Audit ID', 'Risk Level', 'Action Category', 'Action', 'Staff Member', 'Record ID',
        'Before Value', 'After Value', 'Reason', 'Approved By', 'Approval Status', 'Resolution Notes',
      ]),
      tab('metadata', 'Metadata', META_FIELDS, { kind: 'kv' }),
    ],
  },
];

const SCHEMA_BY_ID = Object.fromEntries(REPORT_SCHEMAS.map((s) => [s.id, s]));

function getReportSchema(reportId) {
  return SCHEMA_BY_ID[reportId] || null;
}

function findTabByLabel(schema, sheetLabel) {
  return schema?.tabs.find((t) => t.label === sheetLabel) || null;
}

function catalogFromSchemas() {
  return REPORT_SCHEMAS.map((report) => ({
    id: report.id,
    title: report.title,
    description: report.description,
    status: 'ready',
    tabs: report.tabs.map((t) => ({
      id: t.id,
      label: t.label,
      kind: t.kind,
      fields: t.fields.map((f) => ({ id: f.id, label: f.label })),
    })),
  }));
}

module.exports = {
  REPORT_SCHEMAS,
  getReportSchema,
  findTabByLabel,
  catalogFromSchemas,
  fieldId,
};
