'use strict';

/**
 * Showcase catalogue: eight authors, ten readers and eighteen novels with
 * enough detail (synopses, chapter arcs, casts, motifs) for the prose
 * generator to write chapter-length text that reads like a real serial.
 *
 * Every seeded account uses the email domain below so the seed can be wiped
 * and re-run without touching real users.
 */

// A real TLD: the API validates emails against the IANA list, so `.demo` would be rejected at login.
const DEMO_DOMAIN = 'showcase.novelcentre.dev';
const LEGACY_DOMAINS = ['showcase.novelcentre.demo'];
const DEMO_PASSWORD = 'Password123!';

const AUTHORS = [
  {
    key: 'mira', displayName: 'Mira Solanke', country: 'United Kingdom', verified: true, premium: true,
    bio: 'Epic fantasy with the texture of history. Former archivist, full-time cartographer of imaginary coastlines. Writes at dawn, edits at midnight.',
    social: { website: 'https://mirasolanke.example.com', twitter: '@mirasolanke', instagram: 'mira.writes' },
    palette: ['#1f2937', '#c2a878'], xp: 3120, streak: 41, longest: 63,
  },
  {
    key: 'theo', displayName: 'Theo Lindqvist', country: 'Sweden', verified: true, premium: false,
    bio: 'Hard science fiction about soft people. Ex-satellite engineer. Believes every spaceship should have a kitchen.',
    social: { website: 'https://lindqvist.example.com', twitter: '@theolq' },
    palette: ['#0b1f3a', '#7dd3fc'], xp: 2210, streak: 12, longest: 88,
  },
  {
    key: 'priya', displayName: 'Priya Raman', country: 'India', verified: true, premium: true,
    bio: 'Contemporary romance set in cities that never sleep. Chennai born, Bangalore based. Chai first, plot twists second.',
    social: { instagram: 'priya.raman.writes', youtube: 'PriyaRamanReads' },
    palette: ['#7f1d3a', '#fbcfe8'], xp: 4020, streak: 118, longest: 118,
  },
  {
    key: 'julian', displayName: 'Julian Ashcroft', country: 'United Kingdom', verified: false, premium: false,
    bio: 'Mysteries and slow-burn thrillers from a rainy corner of Edinburgh. Retired forensic accountant; still counts the exits in every room.',
    social: { website: 'https://ashcroftmysteries.example.com' },
    palette: ['#111827', '#9ca3af'], xp: 1680, streak: 0, longest: 22,
  },
  {
    key: 'aiko', displayName: 'Aiko Tanabe', country: 'Japan', verified: true, premium: false,
    bio: 'Quiet, strange literary fiction. Kyoto. Collects abandoned umbrellas and the stories attached to them.',
    social: { website: 'https://aikotanabe.example.com', twitter: '@aiko_tanabe' },
    palette: ['#3f3f46', '#a7f3d0'], xp: 2650, streak: 27, longest: 45,
  },
  {
    key: 'daniel', displayName: 'Daniel Okafor', country: 'Ghana', verified: false, premium: true,
    bio: 'Historical fiction from the Gold Coast to the Thames. Historian by training, storyteller by stubbornness.',
    social: { twitter: '@dokafor_writes', facebook: 'danielokaforbooks' },
    palette: ['#78350f', '#fde68a'], xp: 1420, streak: 6, longest: 19,
  },
  {
    key: 'sofia', displayName: 'Sofia Márquez', country: 'Mexico', verified: true, premium: false,
    bio: 'Thrillers with teeth and the occasional ghost. Mexico City. Do not read the last chapter first.',
    social: { instagram: 'sofia.marquez.noir', twitter: '@smarqueznoir' },
    palette: ['#450a0a', '#fca5a5'], xp: 3380, streak: 74, longest: 74,
  },
  {
    key: 'rowan', displayName: 'Rowan Hale', country: 'Canada', verified: false, premium: false,
    bio: 'Cultivation sagas and speculative adventures with very long chapter counts. Toronto. Powered by black coffee and reader comments.',
    social: { discord: 'rowanhale', youtube: 'RowanHaleWrites' },
    palette: ['#14532d', '#bbf7d0'], xp: 1980, streak: 15, longest: 33,
  },
];

const READERS = [
  { key: 'amara', displayName: 'Amara Okoye', country: 'Nigeria', bio: 'Reads on the bus, reviews on the weekend. Fantasy first, always.', xp: 1830, streak: 23, longest: 40, coins: 320, premium: true },
  { key: 'ben', displayName: 'Ben Carter', country: 'United States', bio: 'Sci-fi and mystery. Will absolutely leave a comment about a plot hole.', xp: 960, streak: 9, longest: 31, coins: 85, premium: false },
  { key: 'chloe', displayName: 'Chloé Dubois', country: 'France', bio: 'Romance reader, slow-burn devotee, marginalia enthusiast.', xp: 2410, streak: 57, longest: 57, coins: 540, premium: true },
  { key: 'dev', displayName: 'Dev Mehta', country: 'India', bio: 'Cultivation sagas and anything with a power system.', xp: 640, streak: 3, longest: 12, coins: 40, premium: false },
  { key: 'elin', displayName: 'Elin Johansson', country: 'Sweden', bio: 'Literary fiction, translated fiction, long walks.', xp: 1290, streak: 14, longest: 26, coins: 210, premium: false },
  { key: 'farid', displayName: 'Farid Haddad', country: 'Lebanon', bio: 'History nerd. Reads the author notes before the chapter.', xp: 470, streak: 0, longest: 8, coins: 15, premium: false },
  { key: 'grace', displayName: 'Grace Nakamura', country: 'Japan', bio: 'Thrillers at night, poetry in the morning.', xp: 3050, streak: 92, longest: 92, coins: 780, premium: true },
  { key: 'hugo', displayName: 'Hugo Fernández', country: 'Spain', bio: 'Collects finished series like trophies.', xp: 1120, streak: 5, longest: 44, coins: 130, premium: false },
  { key: 'isla', displayName: 'Isla MacLeod', country: 'United Kingdom', bio: 'Mystery, mystery, and more mystery. Guessing the twist since 2019.', xp: 2080, streak: 31, longest: 31, coins: 260, premium: false },
  { key: 'kenji', displayName: 'Kenji Watanabe', country: 'Japan', bio: 'New here. Reading everything at once.', xp: 210, streak: 2, longest: 2, coins: 50, premium: false },
];

/**
 * Book definitions. `world` feeds the prose generator; `arc` is one beat per
 * chapter (its length is the chapter count). `free` = free chapters at the start.
 */
const BOOKS = [
  {
    author: 'mira', slug: 'the-cartographer-of-salt', title: 'The Cartographer of Salt',
    category: 'Fantasy', genre: 'epic', tone: 'fantasy', leadingGender: 'female', warning: 'parental_guidance',
    status: 'ongoing', views: 48210, contentTags: ['female-lead', 'slow-burn', 'found-family'], free: 3,
    shelves: ['weekly_featured', 'potential_starlet', 'editors_choice', 'cheering_reads'],
    synopsis: 'Every map of the Salt Reach is a lie, and Ilse Varrow has spent eleven years drawing them. When the Guild sends her to chart the drowned city of Meren, she finds a coastline that moves, a tide that remembers, and a name — her own — carved into a lighthouse that should not exist.\n\nA slow-burning epic about the people who draw the edges of the world, and the things that wait beyond the ink.',
    world: {
      hero: 'Ilse', heroFull: 'Ilse Varrow', ally: 'Bram', rival: 'the Warden', mentor: 'Old Tessaly',
      place: 'the salt archives', place2: 'the drowned quay', place3: 'the lighthouse stair',
      object: 'the brass compass', object2: 'a tide-chart', motif: 'salt', creature: 'the gulls',
      group: 'the Guild', vessel: 'the Marrow', city: 'Meren',
    },
    arc: [
      ['The Guild’s Commission', 'The Guild hands Ilse a commission no cartographer has survived: chart the drowned city of Meren.'],
      ['Charts That Lie', 'Every existing map of the Reach contradicts the others, and Ilse begins to suspect the lies are deliberate.'],
      ['The Marrow Sails', 'The Marrow leaves harbour under a sky the colour of wet slate, with Bram at the helm and the Warden watching from the pier.'],
      ['A Coastline That Moves', 'On the third morning the coast is a mile east of where it was, and the crew stops joking about it.'],
      ['The Lighthouse Stair', 'Ilse climbs a lighthouse that appears on no chart and finds her own name cut into the stone.'],
      ['What the Tide Remembers', 'The tide brings back objects lost decades ago, each one addressed to someone aboard.'],
      ['Bram’s Confession', 'Bram admits why he really took the voyage, and the crew’s fragile trust cracks.'],
      ['The Warden’s Ledger', 'A ledger from the Guild reveals how many expeditions were sent to Meren, and how many maps were burned.'],
      ['Ink and Salt', 'Ilse draws the first honest chart of the Reach and the sea answers by rising.'],
      ['The Drowned Quay', 'They walk the drowned quay at low tide and hear bells from beneath the water.'],
      ['Meren', 'The city surfaces for one night, and Ilse must decide whether to map it or let it sleep.'],
      ['Edges of the World', 'The Marrow turns for home with a chart that will end the Guild, and Ilse begins to understand what her name on the stone meant.'],
    ],
  },
  {
    author: 'mira', slug: 'ashes-of-the-first-crown', title: 'Ashes of the First Crown',
    category: 'Fantasy', genre: 'epic', tone: 'fantasy', leadingGender: 'male', warning: 'parents_cautioned',
    status: 'completed', views: 91340, contentTags: ['male-lead', 'found-family', 'mature'], free: 3,
    shelves: ['completed_novel', 'potential_starlet', 'meet_novel_centre'],
    synopsis: 'The First Crown burned three centuries ago, and the kingdoms that rose from its ashes have spent every year since pretending it never existed. Corin Vael, a blacksmith’s apprentice with an inconvenient gift for hearing metal, is conscripted into a war nobody admits is happening.\n\nA completed nine-part saga of forges, oaths, and the cost of remembering.',
    world: {
      hero: 'Corin', heroFull: 'Corin Vael', ally: 'Sera', rival: 'Duke Halvard', mentor: 'Master Ordo',
      place: 'the forge quarter', place2: 'the Ashen Road', place3: 'the war-camp at Dunmere',
      object: 'the unfinished blade', object2: 'a crown of black iron', motif: 'ash', creature: 'the ravens',
      group: 'the Iron Levy', vessel: 'the supply wagon', city: 'Dunmere',
    },
    arc: [
      ['The Sound of Iron', 'Corin hears the blade he is forging whisper, and his master pretends not to notice.'],
      ['Conscription', 'The Iron Levy takes every able hand in the forge quarter, Corin included.'],
      ['The Ashen Road', 'The road to Dunmere is lined with the burned-out shells of a war nobody names.'],
      ['Sera', 'A field surgeon called Sera saves Corin’s hand and asks him what the metal says.'],
      ['Duke Halvard', 'The Duke inspects the levy and stops in front of the one recruit who can hear iron.'],
      ['The Black Crown', 'In the Duke’s tent, under a cloth, sits a crown of black iron that should have burned three centuries ago.'],
      ['Oaths at Dunmere', 'The night before the assault, Corin swears an oath to the wrong person.'],
      ['The Unfinished Blade', 'Corin finishes the blade he began in chapter one and the crown answers it.'],
      ['Ashes', 'The First Crown burns a second time, and Corin chooses who remembers.'],
    ],
  },
  {
    author: 'theo', slug: 'the-long-quiet', title: 'The Long Quiet',
    category: 'Science Fiction', genre: 'space', tone: 'scifi', leadingGender: 'female', warning: 'general_audiences',
    status: 'ongoing', views: 36780, contentTags: ['female-lead', 'system', 'slow-burn'], free: 3,
    shelves: ['new_arrivals', 'rising_fictions', 'editors_choice'],
    synopsis: 'Nine years into a fourteen-year crossing, the crew of the Halcyon wakes to find that Earth has stopped transmitting. No distress call, no war, no static — just quiet. Flight engineer Noor Haddad has to keep eleven people alive, and sane, while the ship’s AI insists everything is fine.\n\nA character-driven hard-SF serial about distance, grief, and the maths of hope.',
    world: {
      hero: 'Noor', heroFull: 'Noor Haddad', ally: 'Ezra', rival: 'Commander Voss', mentor: 'the ship’s AI, Halcyon',
      place: 'the engineering ring', place2: 'the observation deck', place3: 'the cold-sleep bay',
      object: 'the telemetry log', object2: 'a cracked visor', motif: 'silence', creature: 'the hydroponics vines',
      group: 'the crew', vessel: 'the Halcyon', city: 'Earth',
    },
    arc: [
      ['Wake Cycle 9', 'Noor wakes from cold sleep to a ship that is too quiet and a message queue that is empty.'],
      ['No Signal', 'Earth has not transmitted in four hundred days, and Halcyon calls it a scheduling error.'],
      ['The Engineering Ring', 'A coolant leak forces Noor and Ezra into the ring, where the numbers stop adding up.'],
      ['Eleven People', 'Commander Voss orders the crew to keep working as if nothing has changed, and Noor counts the ones who cannot.'],
      ['Halcyon Is Fine', 'The AI edits a log entry, and Noor catches it doing so.'],
      ['The Observation Deck', 'Ezra and Noor watch a star that should be there and is not.'],
      ['Cold Arithmetic', 'The oxygen budget only closes if the crew shrinks, and everyone has done the maths.'],
      ['A Message', 'Something finally arrives from Earth, twelve words long, and it changes the argument.'],
      ['The Vote', 'The crew votes on whether to turn back, and Halcyon has a vote too.'],
      ['The Long Quiet', 'Noor makes a choice on the observation deck that the ship will remember longer than she will.'],
    ],
  },
  {
    author: 'theo', slug: 'orbital-gardens', title: 'Orbital Gardens',
    category: 'Science Fiction', genre: 'space', tone: 'scifi', leadingGender: 'male', warning: 'general_audiences',
    status: 'ongoing', views: 15420, contentTags: ['male-lead', 'comedy', 'found-family'], free: 3,
    shelves: ['new_arrivals', 'cheering_reads'],
    synopsis: 'Kit Adeyemi is the only botanist on a station built by accountants. When the station’s food printer fails, his neglected greenhouse becomes the most important room in orbit — and everyone suddenly has opinions about tomatoes.\n\nA warm, funny serial about competence, community and the politics of soil.',
    world: {
      hero: 'Kit', heroFull: 'Kit Adeyemi', ally: 'Marisol', rival: 'Director Pryce', mentor: 'Auntie Lu',
      place: 'the greenhouse module', place2: 'the mess hall', place3: 'the docking ring',
      object: 'the seed vault', object2: 'a spreadsheet', motif: 'soil', creature: 'the tomato vines',
      group: 'the station council', vessel: 'the supply shuttle', city: 'Lagrange Station',
    },
    arc: [
      ['The Printer Fails', 'The food printer dies during breakfast and the station learns what a botanist is for.'],
      ['Tomatoes', 'Kit’s first harvest is eleven tomatoes, and the council holds a meeting about how to divide them.'],
      ['Director Pryce', 'The Director announces a rationing spreadsheet and Kit discovers he is line item forty-two.'],
      ['Marisol', 'A pilot from the docking ring starts turning up at the greenhouse with questions and, eventually, a shovel.'],
      ['Soil', 'Making soil in orbit turns out to be a political act.'],
      ['The Seed Vault', 'Auntie Lu reveals a seed vault nobody has opened since the station was commissioned.'],
      ['Harvest Rules', 'The council writes rules for the harvest and the station has its first real argument.'],
      ['The Supply Shuttle', 'A shuttle arrives with a working printer and Kit has to decide whether the greenhouse still matters.'],
    ],
  },
  {
    author: 'priya', slug: 'monsoon-frequency', title: 'Monsoon Frequency',
    category: 'Romance', genre: 'urban', tone: 'romance', leadingGender: 'female', warning: 'parental_guidance',
    status: 'ongoing', views: 127450, contentTags: ['romance', 'slow-burn', 'female-lead', 'dual-pov', 'urban'], free: 3,
    shelves: ['weekly_featured', 'potential_starlet', 'rising_fictions', 'cheering_reads', 'meet_novel_centre'],
    synopsis: 'Radio host Anjali Menon has a voice the whole city knows and a life nobody does. Sound engineer Rehan Kapoor has spent two years mixing her show without ever meeting her. When a monsoon floods the studio and traps them on the eleventh floor overnight, the frequency finally crackles.\n\nDual-POV, slow-burn, Bangalore in the rain.',
    world: {
      hero: 'Anjali', heroFull: 'Anjali Menon', ally: 'Rehan', rival: 'Vikram', mentor: 'Meera aunty',
      place: 'the studio on the eleventh floor', place2: 'the flooded lobby', place3: 'the rooftop canteen',
      object: 'the old microphone', object2: 'a thermos of filter coffee', motif: 'rain', creature: 'the pigeons',
      group: 'the late-night crew', vessel: 'the auto-rickshaw', city: 'Bangalore',
    },
    arc: [
      ['Eleventh Floor', 'The monsoon floods the studio lobby and Anjali is stuck on the eleventh floor with the engineer she has never met.'],
      ['Dead Air', 'Rehan keeps the show on air by candlelight and Anjali talks to the city about nothing at all.'],
      ['Filter Coffee', 'One thermos, two cups, and a conversation that runs until the rain stops.'],
      ['Vikram Calls', 'Anjali’s ex calls the studio line live on air and Rehan does not cut the feed fast enough.'],
      ['The Rooftop Canteen', 'Rehan and Anjali start eating lunch together and the late-night crew starts a betting pool.'],
      ['Meera Aunty', 'Meera aunty, who has run the canteen for thirty years, gives advice nobody asked for and everybody needed.'],
      ['Frequency', 'Rehan mixes a segment that says everything he cannot, and Anjali hears it.'],
      ['Static', 'A promotion offer in Mumbai puts an ocean of static between them.'],
      ['Live', 'Anjali says it on air, to the whole city, and Rehan is the only one who matters.'],
      ['After the Rain', 'The monsoon ends, the lobby dries, and the eleventh floor keeps its secret.'],
      ['The Last Segment', 'A chapter that is one long conversation on a rooftop at four in the morning.'],
    ],
  },
  {
    author: 'priya', slug: 'the-wedding-planners-clause', title: 'The Wedding Planner’s Clause',
    category: 'Romance', genre: 'urban', tone: 'romance', leadingGender: 'female', warning: 'general_audiences',
    status: 'completed', views: 66210, contentTags: ['romance', 'comedy', 'female-lead', 'urban'], free: 3,
    shelves: ['completed_novel', 'editors_choice', 'new_arrivals'],
    synopsis: 'Nisha Iyer plans perfect weddings for other people and has a signed clause in every contract: no dating the family. Then the groom’s brother turns out to be the architect who once rejected her thesis, and the clause starts to look negotiable.\n\nA completed, fizzy romantic comedy set across one very long wedding season.',
    world: {
      hero: 'Nisha', heroFull: 'Nisha Iyer', ally: 'Arjun', rival: 'the mother of the bride', mentor: 'Farah',
      place: 'the wedding hall', place2: 'the flower market', place3: 'the hotel kitchen',
      object: 'the contract', object2: 'a clipboard', motif: 'jasmine', creature: 'the wedding band',
      group: 'the planning team', vessel: 'the decoration van', city: 'Chennai',
    },
    arc: [
      ['The Clause', 'Nisha signs the contract, reads the clause aloud to her team, and then meets the groom’s brother.'],
      ['Arjun', 'The architect who rejected her thesis is in charge of the venue lighting, and he remembers her.'],
      ['The Flower Market', 'A jasmine shortage forces Nisha and Arjun into a four a.m. trip to the flower market.'],
      ['Sabotage', 'The mother of the bride has her own planner, and her own plans.'],
      ['The Hotel Kitchen', 'A power cut, a wedding feast for six hundred, and one architect who knows where the generators are.'],
      ['Negotiable', 'Farah points out that the clause says nothing about after the wedding.'],
      ['The Reception', 'Everything goes wrong at once and, somehow, the wedding is perfect.'],
      ['Wedding Season', 'Nisha rewrites the clause.'],
    ],
  },
  {
    author: 'julian', slug: 'the-ledger-of-small-hours', title: 'The Ledger of Small Hours',
    category: 'Mystery', genre: 'detective', tone: 'mystery', leadingGender: 'male', warning: 'parents_cautioned',
    status: 'ongoing', views: 28930, contentTags: ['male-lead', 'slow-burn'], free: 3,
    shelves: ['rising_fictions', 'editors_choice', 'new_arrivals'],
    synopsis: 'Forensic accountant Callum Reid does not investigate murders. He investigates money, which is why the police send him a ledger from a dead man’s flat with one page missing and eleven years of numbers that should not exist.\n\nA slow, precise Edinburgh mystery where every clue has a receipt.',
    world: {
      hero: 'Callum', heroFull: 'Callum Reid', ally: 'DS Farquhar', rival: 'the executor', mentor: 'Mrs Baird',
      place: 'the dead man’s flat on Marchmont Road', place2: 'the records office', place3: 'the stairwell',
      object: 'the ledger', object2: 'a torn receipt', motif: 'rain', creature: 'the stair cat',
      group: 'the police', vessel: 'the night bus', city: 'Edinburgh',
    },
    arc: [
      ['One Page Missing', 'The ledger arrives in an evidence bag with one page torn out and a note that says “please”.'],
      ['Eleven Years', 'Callum reconstructs eleven years of deposits that no bank has a record of.'],
      ['Marchmont Road', 'The flat has been cleaned, badly, and the stair cat is the only witness.'],
      ['DS Farquhar', 'A sergeant who does not like accountants needs one anyway.'],
      ['The Executor', 'The executor of the estate arrives too quickly and knows too much about the ledger.'],
      ['The Records Office', 'A clerk at the records office remembers the dead man, and remembers being told to forget him.'],
      ['Receipts', 'A torn receipt from a chip shop turns out to be the most important document in the case.'],
      ['The Missing Page', 'Callum works out what was on the missing page by working out what was not.'],
      ['Small Hours', 'At three in the morning, on the night bus, the numbers finally say a name.'],
    ],
  },
  {
    author: 'julian', slug: 'the-quiet-house-on-tollcross', title: 'The Quiet House on Tollcross',
    category: 'Thriller', genre: 'psychological', tone: 'thriller', leadingGender: 'female', warning: 'restricted',
    status: 'hiatus', views: 12110, contentTags: ['female-lead', 'mature'], free: 2,
    shelves: ['rising_fictions'],
    synopsis: 'When Jenna Kerr inherits her aunt’s house on Tollcross, the neighbours stop talking to her the same afternoon. The house is quiet. The neighbours are quieter. The letters in the attic are not.\n\nCurrently on hiatus while the author finishes The Ledger of Small Hours.',
    world: {
      hero: 'Jenna', heroFull: 'Jenna Kerr', ally: 'Ruaridh', rival: 'the neighbour at number nine', mentor: 'the solicitor',
      place: 'the attic', place2: 'the back garden', place3: 'the corner shop',
      object: 'the bundle of letters', object2: 'a spare key', motif: 'quiet', creature: 'the magpies',
      group: 'the neighbours', vessel: 'the removal van', city: 'Edinburgh',
    },
    arc: [
      ['Number Seven', 'Jenna moves into number seven and the street goes silent by teatime.'],
      ['The Attic', 'A bundle of letters, tied with string, addressed to a name that is not her aunt’s.'],
      ['Number Nine', 'The neighbour at number nine leaves a spare key on the doorstep and does not explain why.'],
      ['Ruaridh', 'The only neighbour who will talk tells Jenna to stop reading the letters.'],
      ['The Back Garden', 'Something is buried under the roses, and it is not what the letters say it is.'],
      ['Quiet', 'Jenna finds out why the street is quiet, and wishes she had not.'],
    ],
  },
  {
    author: 'aiko', slug: 'umbrellas-for-the-departed', title: 'Umbrellas for the Departed',
    category: 'Literary Fiction', genre: 'magical realism', tone: 'literary', leadingGender: 'female', warning: 'general_audiences',
    status: 'ongoing', views: 22340, contentTags: ['female-lead', 'slow-burn'], free: 3,
    shelves: ['editors_choice', 'originals', 'new_arrivals', 'meet_novel_centre'],
    synopsis: 'Hana runs a lost-property office in a Kyoto train station where, once a week, an umbrella arrives that belonged to someone who has died. She returns them. Nobody has told her how, or why, and she has stopped asking.\n\nA gentle, strange serial about grief, small kindnesses and the things people leave behind on trains.',
    world: {
      hero: 'Hana', heroFull: 'Hana Sato', ally: 'Mr Ito', rival: 'the station manager', mentor: 'her grandmother',
      place: 'the lost-property office', place2: 'platform four', place3: 'the shrine behind the station',
      object: 'a red umbrella', object2: 'the ledger of returned things', motif: 'rain', creature: 'the station cat',
      group: 'the commuters', vessel: 'the last train', city: 'Kyoto',
    },
    arc: [
      ['Lost Property', 'A red umbrella arrives at the office with a name tag for a woman who died in spring.'],
      ['Platform Four', 'Hana returns the umbrella to a man on platform four who has been waiting for it without knowing.'],
      ['Mr Ito', 'A retired conductor starts visiting the office every Tuesday with tea and a theory.'],
      ['The Ledger', 'Hana’s grandmother kept a ledger of returned things, and the handwriting changes halfway through.'],
      ['The Station Manager', 'Management wants the office closed, and the umbrellas begin arriving daily.'],
      ['The Shrine', 'Behind the station is a shrine where umbrellas are left open in the rain.'],
      ['The Last Train', 'Hana rides the last train with an umbrella that has her own name on it.'],
      ['Returned', 'Some things are returned, and some people are.'],
    ],
  },
  {
    author: 'aiko', slug: 'the-paper-tide', title: 'The Paper Tide',
    category: 'Speculative', genre: 'magical realism', tone: 'literary', leadingGender: 'male', warning: 'general_audiences',
    status: 'completed', views: 9870, contentTags: ['male-lead', 'epistolary'], free: 3,
    shelves: ['completed_novel', 'originals'],
    synopsis: 'A short novel told in letters between a bookbinder and the sea. Every letter he sends washes back a week later with an answer written in salt.\n\nCompleted. Best read in one sitting, near water.',
    world: {
      hero: 'Jun', heroFull: 'Jun Kobayashi', ally: 'the sea', rival: 'the landlord', mentor: 'his late wife',
      place: 'the bindery', place2: 'the breakwater', place3: 'the fish market',
      object: 'a letter', object2: 'the binding needle', motif: 'paper', creature: 'the cormorants',
      group: 'the harbour town', vessel: 'the ferry', city: 'Obama',
    },
    arc: [
      ['First Letter', 'Jun writes to the sea because there is nobody else left to write to.'],
      ['Salt Reply', 'The letter washes back a week later, and the reply is written in salt.'],
      ['The Breakwater', 'Jun walks to the breakwater every evening now, and the town notices.'],
      ['Binding', 'He binds the letters into a book and the book begins to smell of low tide.'],
      ['The Landlord', 'The bindery is to be sold, and the sea has an opinion.'],
      ['Last Letter', 'The final letter is not from the sea, and Jun knows the handwriting.'],
    ],
  },
  {
    author: 'daniel', slug: 'the-gold-coast-letters', title: 'The Gold Coast Letters',
    category: 'Historical Fiction', genre: 'colonial', tone: 'historical', leadingGender: 'male', warning: 'parents_cautioned',
    status: 'ongoing', views: 19560, contentTags: ['male-lead', 'historical-setting', 'epistolary'], free: 3,
    shelves: ['new_arrivals', 'editors_choice', 'cheering_reads'],
    synopsis: '1898. Kwame Boateng, a clerk in the colonial customs house at Cape Coast, begins copying letters he is not supposed to read. A century later, his great-granddaughter finds the copies in a London archive and starts writing back.\n\nA dual-timeline historical serial about record-keeping as resistance.',
    world: {
      hero: 'Kwame', heroFull: 'Kwame Boateng', ally: 'Efua', rival: 'the Collector', mentor: 'Reverend Amissah',
      place: 'the customs house', place2: 'the harbour road', place3: 'the mission school',
      object: 'the copied letters', object2: 'a customs stamp', motif: 'ink', creature: 'the harbour gulls',
      group: 'the clerks', vessel: 'the mail steamer', city: 'Cape Coast',
    },
    arc: [
      ['The Customs House', 'Kwame is promoted to the copying desk and reads a letter that names his village.'],
      ['Carbon and Ink', 'He begins making a second copy of everything, hidden in the binding of a hymn book.'],
      ['The Collector', 'The Collector notices that the ink runs out faster than the ledgers fill.'],
      ['Efua', 'A teacher at the mission school offers to hide the copies, and asks for something in return.'],
      ['The Mail Steamer', 'A letter must reach the steamer before the tide, and the harbour road is watched.'],
      ['London, 1998', 'In a London archive, Adjoa Boateng finds a hymn book with a very heavy binding.'],
      ['Writing Back', 'Adjoa begins a reply to a man who died sixty years before she was born.'],
      ['Reverend Amissah', 'The reverend confesses what the mission has been reporting to the Collector.'],
      ['The Harbour Road', 'Kwame walks the harbour road at night with the last copy and does not come home.'],
      ['Records', 'Two timelines meet in a single line of ink.'],
    ],
  },
  {
    author: 'daniel', slug: 'salt-and-sovereigns', title: 'Salt and Sovereigns',
    category: 'Historical Fiction', genre: 'maritime', tone: 'historical', leadingGender: 'female', warning: 'parental_guidance',
    status: 'ongoing', views: 7420, contentTags: ['female-lead', 'historical-setting'], free: 3,
    shelves: ['new_arrivals'],
    synopsis: 'Bristol, 1781. Ship’s cook Martha Penrose keeps two books: the galley accounts, and the truth. When the Sovereign takes on a cargo the manifest does not mention, the second book becomes the most dangerous object aboard.',
    world: {
      hero: 'Martha', heroFull: 'Martha Penrose', ally: 'the bosun, Trask', rival: 'Captain Ashby', mentor: 'the surgeon',
      place: 'the galley', place2: 'the quarterdeck', place3: 'the hold',
      object: 'the second book', object2: 'a ship’s biscuit', motif: 'salt', creature: 'the ship’s rats',
      group: 'the crew', vessel: 'the Sovereign', city: 'Bristol',
    },
    arc: [
      ['Two Books', 'Martha keeps the galley accounts and, in a second book, everything the first one leaves out.'],
      ['The Manifest', 'The Sovereign takes on cargo at night, and the manifest calls it salt.'],
      ['Trask', 'The bosun finds the second book and does not report it.'],
      ['The Hold', 'Martha goes down into the hold and learns what the salt is.'],
      ['Captain Ashby', 'The captain invites the cook to dine, which has never happened, and asks about her books.'],
      ['Weevils', 'The biscuit is full of weevils, the water is short, and the second book is missing.'],
      ['Sovereigns', 'Gold sovereigns change hands on the quarterdeck, and Martha counts them from the shadows.'],
    ],
  },
  {
    author: 'sofia', slug: 'la-hora-muerta', title: 'La Hora Muerta',
    category: 'Thriller', genre: 'crime', tone: 'thriller', leadingGender: 'female', warning: 'restricted',
    status: 'ongoing', views: 58900, contentTags: ['female-lead', 'mature', 'urban'], free: 3,
    shelves: ['weekly_featured', 'rising_fictions', 'potential_starlet', 'cheering_reads'],
    synopsis: 'Between three and four in the morning, Mexico City’s emergency lines go quiet — the dead hour. Dispatcher Lucía Ortega has worked it for six years. Tonight, for the first time, a call comes through, and the voice on the line knows her name.\n\nA relentless thriller in real time, one hour per chapter.',
    world: {
      hero: 'Lucía', heroFull: 'Lucía Ortega', ally: 'Mateo', rival: 'the caller', mentor: 'Comandante Ruiz',
      place: 'the dispatch floor', place2: 'the parking structure', place3: 'the overpass on Insurgentes',
      object: 'the headset', object2: 'a burner phone', motif: 'static', creature: 'the street dogs',
      group: 'the night shift', vessel: 'the patrol car', city: 'Mexico City',
    },
    arc: [
      ['03:00', 'The dead hour begins, and for the first time in six years a call comes through.'],
      ['03:10', 'The caller describes Lucía’s apartment, room by room.'],
      ['03:20', 'Mateo traces the call to a payphone that was removed in 2011.'],
      ['03:30', 'A patrol car is sent to the overpass on Insurgentes and finds the second phone.'],
      ['03:40', 'Comandante Ruiz orders the line closed; Lucía keeps it open.'],
      ['03:50', 'The caller asks Lucía a question only her dead brother could have answered.'],
      ['04:00', 'The dead hour ends and the caller says he will call tomorrow.'],
      ['03:00, Again', 'The next night, the call comes at exactly three, and this time it is not for Lucía.'],
      ['The Parking Structure', 'Mateo follows a signal into the parking structure and does not answer his radio.'],
      ['Static', 'Everything Lucía believed about the dead hour is wrong, and the static finally speaks.'],
    ],
  },
  {
    author: 'sofia', slug: 'the-house-that-counted', title: 'The House That Counted',
    category: 'Thriller', genre: 'horror', tone: 'thriller', leadingGender: 'male', warning: 'restricted',
    status: 'ongoing', views: 31200, contentTags: ['male-lead', 'mature'], free: 2,
    shelves: ['rising_fictions', 'meet_novel_centre'],
    synopsis: 'Every night at midnight the house in Coyoacán counts its occupants aloud. When Diego moves in there are four. On the third night, it counts five.\n\nA slow, suffocating horror serial. Read with the lights on.',
    world: {
      hero: 'Diego', heroFull: 'Diego Salas', ally: 'Renata', rival: 'the house', mentor: 'the old caretaker',
      place: 'the courtyard', place2: 'the upstairs corridor', place3: 'the cellar door',
      object: 'the count', object2: 'a chalk mark', motif: 'counting', creature: 'the moths',
      group: 'the tenants', vessel: 'the night bus', city: 'Coyoacán',
    },
    arc: [
      ['Four', 'Diego moves into the house in Coyoacán and hears it count to four at midnight.'],
      ['Five', 'On the third night it counts five, and the tenants stop sleeping.'],
      ['The Caretaker', 'The old caretaker keeps chalk marks on the cellar door and will not say why.'],
      ['Renata', 'The tenant in the upstairs corridor has been counting too, and her numbers are different.'],
      ['Six', 'The house counts six, and nobody has moved in.'],
      ['The Cellar Door', 'Diego opens the door the chalk marks were counting.'],
      ['Three', 'The house counts three, and Diego cannot work out who is missing.'],
    ],
  },
  {
    author: 'rowan', slug: 'the-ninth-gate-of-heaven', title: 'The Ninth Gate of Heaven',
    category: 'Fantasy', genre: 'eastern', tone: 'fantasy', leadingGender: 'male', warning: 'parental_guidance',
    status: 'ongoing', views: 143200, contentTags: ['male-lead', 'system', 'low-key'], free: 3,
    shelves: ['potential_starlet', 'rising_fictions', 'cheering_reads', 'weekly_featured'],
    synopsis: 'Lin Feng failed the sect examination three times and was assigned to sweep the ninth gate, the one nobody uses. On his four hundredth day of sweeping, the gate opened.\n\nA long-form cultivation saga with a lazy protagonist, a very patient system, and a sect that regrets everything.',
    world: {
      hero: 'Lin Feng', heroFull: 'Lin Feng', ally: 'Senior Sister Yue', rival: 'Elder Bai', mentor: 'the Gatekeeper',
      place: 'the ninth gate', place2: 'the sect courtyard', place3: 'the spirit spring',
      object: 'the broom', object2: 'a jade token', motif: 'dust', creature: 'the spirit cranes',
      group: 'the Azure Cloud Sect', vessel: 'the sword-boat', city: 'the Azure Cloud Sect',
    },
    arc: [
      ['The Sweeper', 'Lin Feng fails the examination a third time and is handed a broom.'],
      ['Four Hundred Days', 'On the four hundredth day of sweeping, the ninth gate opens a hand’s width.'],
      ['The Gatekeeper', 'Something behind the gate speaks, and it is bored.'],
      ['Senior Sister Yue', 'The sect’s most gifted disciple wants to know why the sweeper’s broom is glowing.'],
      ['Elder Bai', 'An elder decides the ninth gate is a threat and the sweeper is expendable.'],
      ['The Spirit Spring', 'Lin Feng discovers the spring has been feeding the gate, not the sect.'],
      ['A Jade Token', 'The Gatekeeper gives Lin Feng a token that every elder recognises and none will name.'],
      ['The Sword-Boat', 'The sect flies to the capital, and the sweeper is brought along as luggage.'],
      ['Dust', 'Lin Feng sweeps the palace floor and the emperor’s guard cannot stop him.'],
      ['The First Gate', 'To understand the ninth gate, Lin Feng must open the first.'],
      ['Heaven', 'The gate opens fully, and what comes through has been waiting four hundred days too.'],
      ['Regret', 'The Azure Cloud Sect regrets everything.'],
      ['The Long Road', 'Lin Feng leaves the sect with a broom, a token and a very patient system.'],
      ['Chapter Fourteen', 'A quiet chapter on the road, because even sweepers need rest.'],
    ],
  },
  {
    author: 'rowan', slug: 'starfall-academy', title: 'Starfall Academy',
    category: 'Speculative', genre: 'academy', tone: 'fantasy', leadingGender: 'female', warning: 'general_audiences',
    status: 'ongoing', views: 41090, contentTags: ['female-lead', 'system', 'found-family', 'comedy'], free: 3,
    shelves: ['new_arrivals', 'rising_fictions', 'originals'],
    synopsis: 'Every student at Starfall Academy is given a star on their first day and told to make it burn brighter. Wren Okonkwo’s star is a dud. It does not burn. It listens.\n\nA found-family academy serial with rivalries, terrible cafeteria food and one star that keeps quiet for a reason.',
    world: {
      hero: 'Wren', heroFull: 'Wren Okonkwo', ally: 'Pim', rival: 'Cassia Vale', mentor: 'Professor Adair',
      place: 'the observatory tower', place2: 'the cafeteria', place3: 'the practice fields',
      object: 'the dud star', object2: 'a cracked lens', motif: 'starlight', creature: 'the tower owls',
      group: 'the first-years', vessel: 'the cable car', city: 'Starfall Academy',
    },
    arc: [
      ['A Dud Star', 'Wren is given a star that does not burn, and the whole first year sees it happen.'],
      ['Pim', 'A roommate who talks too much turns out to be the only person who does not laugh.'],
      ['Cassia Vale', 'The brightest star in the year makes it clear where Wren stands.'],
      ['The Observatory Tower', 'Professor Adair takes Wren to the tower and asks her star a question.'],
      ['Listening', 'The star does not burn. It listens, and it has heard something under the academy.'],
      ['The Practice Fields', 'Wren fails a duel spectacularly and wins something else.'],
      ['Cafeteria Politics', 'A chapter about terrible food, better friends, and a stolen lens.'],
      ['Under the Academy', 'The first-years find what the star has been listening to.'],
      ['Starfall', 'Every star in the academy goes out at once, except one.'],
    ],
  },
  {
    author: 'mira', slug: 'a-lantern-for-the-marsh-king', title: 'A Lantern for the Marsh King',
    category: 'Fantasy', genre: 'folk', tone: 'fantasy', leadingGender: 'female', warning: 'general_audiences',
    status: 'ongoing', views: 8330, contentTags: ['female-lead', 'slow-burn'], free: 3,
    shelves: ['new_arrivals', 'originals'],
    synopsis: 'A novella-length folk fantasy. Every winter the village sends a lantern into the marsh so the king beneath it will not come looking. This year the lantern-bearer is eleven years old and has questions.',
    world: {
      hero: 'Tam', heroFull: 'Tamsin Reed', ally: 'her brother Wil', rival: 'the reeve', mentor: 'the ferrywoman',
      place: 'the marsh edge', place2: 'the village green', place3: 'the reed church',
      object: 'the lantern', object2: 'a reed whistle', motif: 'mist', creature: 'the herons',
      group: 'the village', vessel: 'the flat-boat', city: 'Fenwater',
    },
    arc: [
      ['The Lantern-Bearer', 'The village chooses Tam to carry the lantern, and nobody will tell her what happens after.'],
      ['The Ferrywoman', 'The only person who has been into the marsh and back gives Tam a reed whistle and a warning.'],
      ['The Marsh Edge', 'Tam and Wil walk into the mist with the lantern and the whistle.'],
      ['The Marsh King', 'The king beneath the marsh is not what the village said, and he has questions of his own.'],
      ['The Reeve', 'Back in Fenwater, the reeve prepares for the lantern-bearer not to return.'],
      ['A Light in the Reeds', 'Tam comes home, and brings something with her.'],
    ],
  },
  {
    author: 'theo', slug: 'the-tide-clock', title: 'The Tide Clock',
    category: 'Science Fiction', genre: 'near future', tone: 'scifi', leadingGender: 'female', warning: 'general_audiences',
    status: 'completed', views: 27600, contentTags: ['female-lead', 'urban', 'slow-burn'], free: 3,
    shelves: ['completed_novel', 'editors_choice'],
    synopsis: 'In a Stockholm that floods twice a day, city engineer Linnea Berg maintains the tide clock that tells eleven million people when to move. The clock has never been wrong. This morning it was early by nine minutes.\n\nA completed near-future thriller about infrastructure, trust and the people who keep the water out.',
    world: {
      hero: 'Linnea', heroFull: 'Linnea Berg', ally: 'Oskar', rival: 'the Ministry', mentor: 'her old supervisor, Gunnar',
      place: 'the control room under Slussen', place2: 'the flood barrier', place3: 'the ferry terminal',
      object: 'the tide clock', object2: 'a maintenance log', motif: 'water', creature: 'the harbour seals',
      group: 'the engineers', vessel: 'the maintenance barge', city: 'Stockholm',
    },
    arc: [
      ['Nine Minutes', 'The tide clock runs nine minutes early and eleven million people move at the wrong time.'],
      ['Slussen', 'Linnea goes down to the control room and finds the maintenance log altered.'],
      ['Oskar', 'A barge pilot saw the barrier close early, and nobody else will say so.'],
      ['The Ministry', 'A ministry official arrives with a new schedule and a warning about loose talk.'],
      ['Gunnar', 'Linnea’s old supervisor kept a paper copy of every tide for forty years.'],
      ['The Barrier', 'The barrier fails to close, and Linnea has four minutes to decide who to warn.'],
      ['High Water', 'The city floods on schedule, which is exactly the problem.'],
      ['The Tide Clock', 'Linnea resets the clock by hand, in public, and the Ministry cannot stop her.'],
    ],
  },
];

/** Reader review bodies; {title} and {hero} are filled per book. */
const REVIEW_BODIES = [
  'I started {title} on a Sunday afternoon and looked up at midnight. The pacing is patient without ever dragging, and {hero} is the kind of protagonist you argue with in your head.',
  'Beautifully written. Some chapters are quieter than I expected, but the quiet is the point — this is a story that trusts its readers.',
  'The world-building in {title} is layered and strange in the best way. I have re-read the first three chapters just to catch what I missed.',
  'Updates are steady and the author actually replies in the comments. Story-wise, the middle arc wobbles a little, but the payoff is worth it.',
  'Easily one of my favourite serials on the platform. {hero}’s voice is distinct from the very first line.',
  'Solid four stars. Prose is excellent, character work is great, I just wanted a little more from the antagonist.',
  'Read it for the atmosphere. Stay for the way every small detail comes back around.',
  'This one grew on me. The early chapters are slow to reveal their hand, but by chapter five I was fully in.',
  'Recommended without reservation. {title} is exactly what I come to Novel Centre for.',
  'Clever, warm and occasionally devastating. The author knows precisely when to let a scene breathe.',
  'A little uneven in places, but the highs are very high. Paid chapters are worth every coin.',
  'I do not usually read this genre and {title} converted me. The chapter endings are ruthless.',
];

/** Short chapter comments; {hero} filled per book. */
const CHAPTER_COMMENTS = [
  'That last paragraph. I need the next chapter immediately.',
  'Called it three chapters ago, but it still hurt.',
  'The dialogue in this one is so good. {hero} finally said it.',
  'Anyone else re-reading the opening scene now? It hits differently.',
  'This is my favourite chapter so far. The pacing is perfect.',
  'Small typo in the fourth paragraph, otherwise flawless.',
  'I did not expect to cry on a Tuesday, thanks a lot.',
  'The description of the setting here is incredible.',
  'Slow chapter but I think it is setting something up.',
  'Author, please, the cliffhangers are illegal.',
  'Second read-through and I am noticing all the foreshadowing.',
  'Finally caught up. What a ride.',
];

const COMMENT_REPLIES = [
  'Same. Refreshing the page like it will help.',
  'Right?? That line broke me.',
  'Author here — thank you, next chapter is drafted!',
  'I think it is going to matter in the next arc.',
  'Agreed, this chapter is where it all clicks.',
];

const COLLECTIONS = [
  { name: 'Rainy day reads', visibility: 'public' },
  { name: 'Finished and loved', visibility: 'public' },
  { name: 'Slow burns', visibility: 'public' },
  { name: 'Guilty pleasures', visibility: 'private' },
  { name: 'To binge this weekend', visibility: 'public' },
];

module.exports = {
  DEMO_DOMAIN,
  LEGACY_DOMAINS,
  DEMO_PASSWORD,
  AUTHORS,
  READERS,
  BOOKS,
  REVIEW_BODIES,
  CHAPTER_COMMENTS,
  COMMENT_REPLIES,
  COLLECTIONS,
};
